image: nixos/nix:latest

stages:
  - build

build:pages:
  stage: build
  script:
    - nix-shell --command 'nimble refresh'
    - nix-shell --command 'nimble install --depsOnly'
    - nix-shell --command 'nimble web'
  artifacts:
    paths:
      - public
